In [339]:
import numpy as np
from numpy import linalg as la

In [173]:
def skew_3d(omega):

    omega_hat = np.matrix([[0, -omega.item(2), omega.item(1)],
        [omega.item(2), 0, -omega.item(0)],
        [-omega.item(1), omega.item(0), 0]])
    return omega_hat

In [70]:
identity = np.identity(3)

In [216]:
def rod_formula(w, theta):
    w_hat = skew_3d(w)
    w_hat_square = np.dot(w_hat, w_hat)
    exp = identity + np.sin(theta) * w_hat + w_hat_square*(1 - np.cos(theta))
    return exp

In [217]:
def translation(exp, w, v, theta):
    a = (identity - exp)
    b = (np.cross(w.reshape(1,3), v.reshape(1,3)))
    b = b.reshape(3,1)
    c = np.dot(w, np.transpose(w))
    d = (np.dot(c, v))
    return  a * b + d * theta

In [218]:
def getTwist(exp, trans):
    twist = np.zeros((4,4))
    twist[0:3, 0:3] = exp
    twist[0:3, 3:4] = trans
    twist[3, 3] = 1
    return twist

In [285]:
# Twist 1:
w = np.array([0, 0, 1])
w = w.reshape(3,1)
theta = 0.785
exp = rod_formula(w, theta)
v = np.array([0,0,0])
v = v.reshape(3,1)
trans = translation(exp, w, v, theta)
twist1 = getTwist(exp, trans)
print("twist1:")
print(twist1)

twist1:
[[ 0.70738827 -0.70682518  0.          0.        ]
 [ 0.70682518  0.70738827  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [286]:
# Twist 2:
w = np.array([-1, 0, 0])
w = w.reshape(3,1)
theta = -1.181
exp = rod_formula(w, theta)
v = np.array([0,-5,0])
v = v.reshape(3,1)
trans = translation(exp, w, v, theta)
twist2 = getTwist(exp, trans)
print("twist2:")
print(twist2)

twist2:
[[ 1.          0.          0.          0.        ]
 [ 0.          0.38000003 -0.92498647  4.62493237]
 [ 0.          0.92498647  0.38000003  3.09999986]
 [ 0.          0.          0.          1.        ]]


In [416]:
start = np.matrix([[1,0,0,0],
                            [0,1,0,0],
                            [0,0,1,5],
                            [0,0,0,1]])
print(start)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 5]
 [0 0 0 1]]


In [417]:
print('Gwb:')
Gwb = twist1  * (twist2 * start)
print(Gwb)

Gwb:
[[ 0.70738827 -0.26859359  0.65380373  0.        ]
 [ 0.70682518  0.26880756 -0.65432458  0.        ]
 [ 0.          0.92498647  0.38000003  5.        ]
 [ 0.          0.          0.          1.        ]]


In [290]:
# Twist 3:
w = np.array([-1, 0, 0])
w = w.reshape(3,1)
theta = 2.301
exp = rod_formula(w, theta)
v = np.array([0,-5,4])
v = v.reshape(3,1)
trans = translation(exp, w, v, theta)
twist3 = getTwist(exp, trans)
print("twist3:")
print(twist3)

twist3:
[[ 1.          0.          0.          0.        ]
 [ 0.         -0.66702139  0.74503856  2.94289276]
 [ 0.         -0.74503856 -0.66702139 11.31526122]
 [ 0.          0.          0.          1.        ]]


In [291]:
# Twist 4:
w = np.array([0, 0, 1])
w = w.reshape(3,1)
theta = -1.160
exp = rod_formula(w, theta)
v = np.array([7,0,0])
v = v.reshape(3,1)
trans = translation(exp, w, v, theta)
twist4 = getTwist(exp, trans)
print("twist4:")
print(twist4)

twist4:
[[ 0.39933953  0.91680311  0.         -6.41762176]
 [-0.91680311  0.39933953  0.          4.20462329]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [309]:
start = np.matrix([[1,0,0,0],
                    [0,1,0,7],
                    [0,0,1,5],
                    [0,0,0,1]])
print(start)

[[1 0 0 0]
 [0 1 0 7]
 [0 0 1 5]
 [0 0 0 1]]


In [312]:
Gwd = twist1 * (twist2 * (twist3 * (twist4 * start)))
print('Gwd(Short Version):')
print(np.around(Gwd,decimals = 2))
print('Gwd(Accurate Version):')
print(Gwd)

Gwd(Short Version):
[[ 0.56  0.53 -0.64 -2.  ]
 [-0.    0.77  0.64  2.  ]
 [ 0.83 -0.36  0.44  6.  ]
 [ 0.    0.    0.    1.  ]]
Gwd(Accurate Version):
[[ 0.56481883  0.52555863 -0.63621366 -1.99822833]
 [-0.00029241  0.77109463  0.63672049  1.9998202 ]
 [ 0.82521488 -0.35944569  0.43568245  5.99964457]
 [ 0.          0.          0.          1.        ]]


In [313]:
# Twist 5:
w = np.array([-1, 0, 0])
w = w.reshape(3,1)
theta = - 0.690
exp = rod_formula(w, theta)
v = np.array([0,-5,7])
v = v.reshape(3,1)
trans = translation(exp, w, v, theta)
twist5 = getTwist(exp, trans)
print("twist5:")
print(twist5)

twist5:
[[ 1.          0.          0.          0.        ]
 [ 0.          0.77124601 -0.63653718  4.78396381]
 [ 0.          0.63653718  0.77124601 -3.31199035]
 [ 0.          0.          0.          1.        ]]


In [314]:
# Twist 6:
w = np.array([0, 1, 0])
w = w.reshape(3,1)
theta = 0.970
exp = rod_formula(w, theta)
v = np.array([-5,0,0])
v = v.reshape(3,1)
trans = translation(exp, w, v, theta)
twist6 = getTwist(exp, trans)
print("twist6:")
print(twist6)

twist6:
[[ 0.56529953  0.          0.82488571 -4.12442857]
 [ 0.          1.          0.          0.        ]
 [-0.82488571  0.          0.56529953  2.17350234]
 [ 0.          0.          0.          1.        ]]


In [332]:
start = np.matrix([[1,0,0,0],
                    [0,1,0,7],
                    [0,0,1,5],
                    [0,0,0,1]])
print(start)
final = np.matrix([[1,0,0,0],
                    [0,1,0,2],
                    [0,0,1,0],
                    [0,0,0,1]])

[[1 0 0 0]
 [0 1 0 7]
 [0 0 1 5]
 [0 0 0 1]]


In [338]:
Gwg = twist1 * (twist2 * (twist3 * (twist4 * (twist5 * (twist6  * start))))) * final
print('Gwg(Short Version):')
print(np.around(Gwg, decimals = 2))
print('Gwg(Accurate Version):')
print(Gwg)

Gwg(Short Version):
[[ 1.  0. -0. -2.]
 [-0.  1. -0.  4.]
 [ 0.  0.  1.  6.]
 [ 0.  0.  0.  1.]]
Gwg(Accurate Version):
[[ 0.99999977  0.00036135 -0.00058259 -1.99750563]
 [-0.00036141  0.99999993 -0.00010681  3.99982006]
 [ 0.00058255  0.00010702  0.99999982  5.99985862]
 [ 0.          0.          0.          1.        ]]


In [504]:
aaaaa
a
a
def pk1(p, q, r, w):
    u = p - r
    v = q - r
    uPrime = u - w * w.transpose() * u
    vPrime = v - w * w.transpose() * v
    para1 = w.transpose()*(np.cross(uPrime.transpose(), vPrime.transpose())).transpose()
    para2 = uPrime.transpose()*vPrime
    return np.arctan2(para1, para2)

In [537]:
def pk2(p, q, r, w2, w1):
    u = p - r
    v = q - r
    alpha = ((np.transpose(w1)*w2) * np.transpose(w2)*u - np.transpose(w1)*v)/((np.transpose(w1)*w2) * (np.transpose(w1)*w2) - 1)
    alpha = alpha[0].item(0)
    beta = ((np.transpose(w1)*w2)*np.transpose(w1)*v - np.transpose(w2)*u)/((np.transpose(w1)*w2) * (np.transpose(w1)*w2) - 1)
    beta = beta[0].item(0)
    a = (la.norm(u)*la.norm(u) - alpha*alpha - beta*beta - 2*alpha*beta*np.transpose(w1)*w2)
    b = (np.power(la.norm(np.cross(np.transpose(w1), np.transpose(w2))), 2))
    gammaSquare = a/b
    if gammaSquare.all() < 0:
        return 'None'
    else:
        gamma = np.sqrt(gammaSquare).item(0)
        negativeGamma = -gamma
        z1 = alpha * w1 + beta * w2 + gamma*(np.transpose(np.cross(np.transpose(w1), np.transpose(w2))))
        z2 = alpha * w1 + beta * w2 + negativeGamma*(np.transpose(np.cross(np.transpose(w1), np.transpose(w2))))
        c1 = z1 + r
        c2 = z2 + r
        allC = (c1, c2)
        i = 0
        theta = [None] * len(allC)
        for c in allC:
            theta[i] = (pk1(c, q, r, w1)[0].item(0), pk1(p, c, r, w2)[0].item(0))
            i += 1
        return theta

In [542]:
p = np.matrix([[0],[2],[2.764]])
q = np.matrix([[-2],[2],[6]])
r = np.matrix([[0],[0],[5]])
w1 = np.matrix([[0],[0],[1]])
w2 = np.matrix([[-1],[0],[0]])
thetas = pk2(p,q,r,w2,w1)
print("thetas12:")
print(thetas)

thetas12:
[(-2.356194490192345, 2.6403819701236877), (0.7853981633974483, -1.1808964449373613)]


In [543]:
p = np.matrix([[0],[9],[5]])
q = np.matrix([[1.414],[7.617],[6.273]])
r = np.matrix([[0],[7],[5]])
w1 = np.matrix([[0],[0],[1]])
w2 = np.matrix([[-1],[0],[0]])
thetas = pk2(p,q,r,w2,w1)
print('thetas45:')
print(thetas)

thetas45:
[(1.982241768506251, -2.4516408632162285), (-1.1593508850835421, -0.6899517903735647)]


In [544]:
p = np.matrix([[0],[9],[6]])
q = np.matrix([[0.825],[9],[5.565]])
r = np.matrix([[0],[7],[5]])
w = np.matrix([[0],[1],[0]])
theta = pk1(p, q, r, w)
print('theta6:')
print(theta)

theta6:
[[0.97031171]]
